env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:react-hooks/recommended'
  - 'plugin:json/recommended'
  - 'plugin:jsdoc/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - import
rules: {}
